spring:
  application:
    name: user-service
server:
  port: 4003
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000    
    
ribbon: #对所以服务器做配置这个是默认配置可以不写
  connectionTimeOut: 1000
  ReadTimeOut: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
    
management:
  endpoints:
    web:
      exposure:
       include: hystrix.stream #配置监控端点